// <auto-generated />
using System;
using ExamCourseAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamCourseAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ExamContract.Auth.Key", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Role")
                        .HasMaxLength(20);

                    b.HasKey("Name");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("ExamContract.CourseModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ExamContract.CourseModels.ExamCourse", b =>
                {
                    b.Property<int>("CourseId");

                    b.Property<int>("Id");

                    b.HasKey("CourseId", "Id");

                    b.ToTable("ExamCourses");
                });

            modelBuilder.Entity("ExamContract.CourseModels.TutorialCourse", b =>
                {
                    b.Property<int>("CourseId");

                    b.Property<int>("Id");

                    b.HasKey("CourseId", "Id");

                    b.ToTable("TutorialCourses");
                });

            modelBuilder.Entity("ExamContract.CourseModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("CourseId");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamContract.CourseModels.ExamCourse", b =>
                {
                    b.HasOne("ExamContract.CourseModels.Course")
                        .WithMany("ExamCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ExamContract.CourseModels.TutorialCourse", b =>
                {
                    b.HasOne("ExamContract.CourseModels.Course")
                        .WithMany("TutorialCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ExamContract.CourseModels.User", b =>
                {
                    b.HasOne("ExamContract.CourseModels.Course")
                        .WithMany("Users")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
