//@URL = https://exammaindatabaseapi.azurewebsites.net/api
@URL = http://localhost:12345/api

###
GET {{URL}}/Questions

###
GET {{URL}}/Exams
api-key: admin-key
###

###
GET {{URL}}/Questions/2

###

POST {{URL}}/Exams
content-type: application/json

{
    "name": "Test",  
    "MinStart": "2019-01-01 20:21",
    "MaxStart": "2019-01-02 05:20",
    "DurationMinutes": 90,
    "Login": "ja"
}

###

POST {{URL}}/Questions
content-type: application/json

{
    "question": "doTestowania",
    "image": null,
    "answerType": "wielokrotny"
}
###

PUT {{URL}}/Questions/3
content-type: application/json

{
    "id":3,
    "question": "do Testowania",
    "image": null,
    "answerType": "wielokrotny"
}

###

Delete {{URL}}/Questions/3

###

###
GET {{URL}}/Answers

###
GET {{URL}}/Answers/2

###

POST {{URL}}/Answers
content-type: application/json

{
    "answer": "nie",
}
###

PUT {{URL}}/Answers/3
content-type: application/json

{
    "id":3,
    "answer": "chyba nie",
}

###

Delete {{URL}}/exams/3

###
GET {{URL}}/QuestionWithAnswers/7

###

GET {{URL}}/Keys/admin-key
api-key: admin-key
###


GET {{URL}}/Keys
api-key: admin-key7
###

POST {{URL}}/Keys
content-type: application/json
api-key: admin-key

{
  "name": "admin-key7",
  "role": "teacher",
  "expirationDate": "2020-12-12 00:00:00"
}
###

PUT {{URL}}/Keys/admin-key7
content-type: application/json
api-key: admin-key

{
  "name": "admin-key7",
  "role": "student",
  "expirationDate": "2020-12-31 20:01:00"
}

###

Delete {{URL}}/Keys/admin-key7
api-key: admin-key