// <auto-generated />
using System;
using ExamMailSenderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamMailSenderAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190601100821_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamMailSenderAPI.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content");

                    b.Property<string>("FileName");

                    b.Property<int?>("MailModelId");

                    b.HasKey("Id");

                    b.HasIndex("MailModelId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ExamMailSenderAPI.Models.MailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("From");

                    b.Property<string>("HtmlBody");

                    b.Property<string>("Title");

                    b.Property<string>("ToStr");

                    b.HasKey("Id");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("ExamMailSenderAPI.Models.Attachment", b =>
                {
                    b.HasOne("ExamMailSenderAPI.Models.MailModel")
                        .WithMany("Attachments")
                        .HasForeignKey("MailModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
