// <auto-generated />
using System;
using ExamMailSenderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamMailSenderAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamContract.MailingModels.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<byte[]>("Content");

                    b.Property<string>("FileName");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<int>("MailModelId");

                    b.HasKey("Id");

                    b.HasIndex("MailModelId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ExamContract.MailingModels.MailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Body");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("From");

                    b.Property<string>("HtmlBody");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<string>("Title");

                    b.Property<string>("ToStr");

                    b.HasKey("Id");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("ExamContract.MailingModels.Attachment", b =>
                {
                    b.HasOne("ExamContract.MailingModels.MailModel")
                        .WithMany("Attachments")
                        .HasForeignKey("MailModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
