// <auto-generated />
using System;
using ExamMainDataBaseAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamMainDataBaseAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191226102416_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ExamContract.Auth.Key", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Role")
                        .HasMaxLength(20);

                    b.HasKey("Name");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Content");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<decimal>("Points");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(5);

                    b.Property<int>("DurationMinutes");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<DateTime>("MaxStart");

                    b.Property<DateTime>("MinStart");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.ExamApproache", b =>
                {
                    b.Property<int>("ExamId");

                    b.Property<string>("Login");

                    b.Property<int>("DetailsId");

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("Start");

                    b.HasKey("ExamId", "Login");

                    b.ToTable("ExamApproaches");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.ExamApproacheResult", b =>
                {
                    b.Property<string>("Login");

                    b.Property<int>("ExamId");

                    b.Property<int>("QuestionId");

                    b.Property<int>("AnswerId");

                    b.Property<bool>("Checked");

                    b.Property<decimal>("Points");

                    b.HasKey("Login", "ExamId", "QuestionId", "AnswerId");

                    b.ToTable("ExamApproacheResults");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("AnswerType");

                    b.Property<string>("Content");

                    b.Property<int?>("ExamId");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("ExamId");

                    b.Property<string>("Login")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.Answer", b =>
                {
                    b.HasOne("ExamContract.MainDbModels.Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ExamContract.MainDbModels.Question", b =>
                {
                    b.HasOne("ExamContract.MainDbModels.Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId");
                });

            modelBuilder.Entity("ExamContract.MainDbModels.User", b =>
                {
                    b.HasOne("ExamContract.MainDbModels.Exam")
                        .WithMany("Users")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
