@URL = http://localhost:22333

###
GET {{URL}}/api/Tutorials

###
GET {{URL}}/api/tutorials/2
Accept: application/json

###
POST {{URL}}/api/tutorials
content-type: application/json

{
    "courseId": 2,
    "id": 2
}


{
  "id": 0,
  "name": "TEST 2",
  "file": [123,221,0,1],
  "fileType": "pdf",
  "content": "treść",
  "description" : "Opis",
  "login" : "a@a.a"
}

### 
PUT {{URL}}/api/tutorials/2
content-type: application/json

{
  "id": 2,
  "name": "TEST 21",
  "file": [123,221,0,1],
  "fileType": "pdf",
  "content": "treść",
  "description" : "Opis",
  "login" : "a@a.a"
}

###
DELETE  {{URL}}/api/tutorials/6