//@URL = https://exammailsender.azurewebsites.net/api/
@URL = http://localhost:22333/api

###
GET {{URL}}/courses
//api-key: mailKey

###

POST {{URL}}/courses
content-type: application/json
//api-key: mailKey

{
  "id": 0,
  "login": "a@a.a",
  "active" : true,
  "name" : "Pierwszy kurs",
  "description": "Opis do kursu"
}

###

POST {{URL}}/users
content-type: application/json
//api-key: mailKey

{
  "id": 0,
  "login": "b@b.b",
  "active" : true,
  "courseId" : 1
}
###
GET {{URL}}/tutorials
###
GET {{URL}}/tutorials?course=1

###

POST {{URL}}/tutorials
content-type: application/json
//api-key: mailKey

{  
  "courseId" : 1,
  "id": 1
}

###

DELETE {{URL}}/tutorials/1/1
content-type: application/json
//api-key: mailKey

{  
  "courseId" : 1,
  "id": 1
}